### PR TITLE
fix: support http(s) multiaddr with no tcp port

### LINKED ISSUE #121: DNS multiaddr format support missing: `/dns/hostname/https`
## Description

The `multiaddrToHttpUrl` function fails to correctly parse DNS-based multiaddresses that don't include a TCP port segment, which is a valid format according to the multiaddr spec.

When attempting to parse addresses like `/dns/f03303347-market.duckdns.org/https`, the function throws an error because it expects a TCP protocol and port before the HTTP/HTTPS scheme.

## Reproduction Steps

This issue occurs when processing retrieval requests from certain providers that use the direct DNS format in their multiaddresses. For example, when attempting to fetch content identified by CID `bafyreiaxqptvdcxmyiwhb5kpvkmaxv5e3svniomf6ptvxvl7ypnmlrs22a` from a provider using this address format, we see the following error:

```
Error: Cannot parse "/dns/f03303347-market.duckdns.org/https": unsupported protocol "https"
```

## Expected Behavior

For a multiaddr like `/dns/f03303347-market.duckdns.org/https`, the function should return the URL `https://f03303347-market.duckdns.org`.

## Proposed Solution

Add support for DNS-based direct HTTP/HTTPS format by modifying the `multiaddrToHttpUrl` function to handle this case. The solution should:

1. Detect when a multiaddr contains a DNS host (`/dns/`, `/dns4/`, or `/dns6/`) followed directly by an HTTP or HTTPS protocol identifier
2. Correctly extract the scheme and host in this case, without requiring the TCP port segment
3. Build and return the appropriate URL

## Additional Test Cases

To verify the solution, we should add test cases for this direct format:

```javascript
// Direct DNS format tests
['/dns/meridian.space/https', 'https://meridian.space'],
['/dns/meridian.space/http', 'http://meridian.space']
```

These would complement our existing tests for the TCP-based format and HTTP path format.

Related to https://github.com/CheckerNetwork/spark-checker/issues/112 and https://github.com/CheckerNetwork/roadmap/issues/231

### PR DESCRIPTION
**Pull request by NikolasHaimerl**
## Description

This PR adds support for parsing multiaddresses in the direct DNS + HTTP(S) format, which doesn't include a TCP port segment.

Previously, our multiaddr parser could handled addresses with dns following the `/dns/hostname/tcp/port/http(s)` pattern, but we encountered addresses in the wild using the more concise format: `/dns/hostname/http(s)`. The current implementation would throw an "unsupported protocol" error when encountering these valid addresses.

## Changes
- Added a condition to detect and properly handle DNS-based addresses with direct HTTP/HTTPS protocol specification
- Extended test cases to cover the new format
- Maintained backward compatibility with all existing multiaddr formats

## Examples of newly supported formats:

```
/dns/meridian.space/https → https://meridian.space
/dns/meridian.space/http → http://meridian.space
```

## Testing

All existing tests continue to pass, and new tests for the direct DNS format were added to verify the implementation. I've also manually verified that the updated parser correctly handles the problematic provider multiaddress that was failing in production.

## Related Issues
https://github.com/CheckerNetwork/roadmap/issues/250

Closes #121

### CODE REVIEW

**Comment by NikolasHaimerl** [comment]
Manual test of manuel-check succeeds:

```bash
zinnia run manual-check.js

Calling Filecoin JSON-RPC to get PeerId of miner f03303347
Found peer id: 12D3KooWJ91c6xQshrNe7QAXPFAaeRrHWq2UrgXGPf8UmMZMwyZ5
Querying IPNI to find retrieval providers for bafyreiaxqptvdcxmyiwhb5kpvkmaxv5e3svniomf6ptvxvl7ypnmlrs22a
IPNI returned 4 provider results
Fetching: https://f03303347-market.duckdns.org/ipfs/bafyreiaxqptvdcxmyiwhb5kpvkmaxv5e3svniomf6ptvxvl7ypnmlrs22a?dag-scope=block
Testing HEAD request: https://f03303347-market.duckdns.org/ipfs/bafyreiaxqptvdcxmyiwhb5kpvkmaxv5e3svniomf6ptvxvl7ypnmlrs22a?dag-scope=block
Measurement: {
  cid: "bafyreiaxqptvdcxmyiwhb5kpvkmaxv5e3svniomf6ptvxvl7ypnmlrs22a",
  minerId: "f03303347",
  indexerResult: "OK",
  statusCode: 200,
  byteLength: 303,
  providerId: "12D3KooWJ91c6xQshrNe7QAXPFAaeRrHWq2UrgXGPf8UmMZMwyZ5",
  protocol: "http",
  providerAddress: "/dns/f03303347-market.duckdns.org/https",
  startAt: 2025-03-13T16:54:58.530Z,
  carChecksum: "1220d6337701df29192f0112e16220fa829b683ec87e3ad76d46bf938c31a472ac26",
  endAt: 2025-03-13T16:55:00.198Z,
  headStatusCode: 405
}
```

File: lib/multiaddr.js
Comment (bajtos) [inline lib/multiaddr.js:1]: I feel the pull request title does not explain what is changing. Let's improve the title to mention the fact that it adds support for addresses with no explicit port specified.

For example:
```
fix: support http(s) multiaddr with no tcp port
```

File: lib/multiaddr.js [hunk 1]
```diff
@@ -17,7 +17,10 @@ export function multiaddrToHttpUrl (addr) {
         new Error(`Cannot parse "${addr}": unsupported http path`, { cause: err }),
         { code: 'INVALID_HTTP_PATH' }
       )
-    }
+    } // Handle DNS-based direct http/https format
+  } else if (hostType.startsWith('dns') && (multiAddrParts[0] === 'http' || multiAddrParts[0] === 'https')) {
```
Comment (bajtos) [inline lib/multiaddr.js:21]: Can we make this code generic to support other host types than `dns`? I remember that many SPs use IPv4 address instead. Take a look at the function `getUriHost` to see all the different host types to support.

An example test case to add:

```js
  ['/ip4/127.0.0.1/http', 'http://127.0.0.1'],
```

Suggested fix:

```suggestion
    } 
  // Handle HTTP/HTTPs addresses using the default port
  } else if (multiAddrParts[0] === 'http' || multiAddrParts[0] === 'https') {
```

File: lib/multiaddr.js [hunk 2]
```diff
@@ -17,7 +17,10 @@ export function multiaddrToHttpUrl (addr) {
...
+    scheme = multiAddrParts[0]
+    rest = multiAddrParts.slice(1)
```
Comment (bajtos) [inline lib/multiaddr.js:23]: Is it worth simplifying this for consistency with the style we use below?

```suggestion
    ;[scheme, ...rest] = multiAddrParts[0]
```

File: manual-check.js
Comment (bajtos) [inline manual-check.js:1]: Please revert the changes in this file. The vanilla configuration for the manual check is intentionally using CID hosted by our Frisbii instance.

**Review by bajtos — CHANGES_REQUESTED** [review]
Great start!

File: manual-check.js
Comment (NikolasHaimerl) [reply manual-check.js:1]: Sure, I left them in to make it easier to reproduce the manual check that I mentioned.

File: lib/multiaddr.js (hunk 1 above)
Comment (NikolasHaimerl) [reply lib/multiaddr.js]: Addressed in b71f5fc

File: lib/multiaddr.js (hunk 2 above)
Comment (NikolasHaimerl) [reply lib/multiaddr.js]: Addressed in https://github.com/CheckerNetwork/spark-checker/commit/b71f5fc598ae9dd39273feacee240c53d1ce4f52

File: manual-check.js
Comment (NikolasHaimerl) [reply manual-check.js:1]: Addressed in https://github.com/CheckerNetwork/spark-checker/commit/b71f5fc598ae9dd39273feacee240c53d1ce4f52

**Review by bajtos — APPROVED** [review]
👏🏻

**Review by juliangruber — COMMENTED** [review]
👏

**Comment by xiaoliwe** [comment]
@NikolasHaimerl,Hi buddy, If I want to test it with "Zinnia run manual-check.js," I just need to modify the minerID and peerID in manual-check.js.  Thanks.
